// Auto-curated from https://supremesportrental.com/pages/do-not-rent-list
// License IDs are null on import — the source page renders them as images, not text.
// Companies fill in the license ID after upload (manually or via OCR step).

export type SeedEntry = {
  fullName: string;
  primaryReason: string;
  detailedNotes?: string;
  categories: string[];
  severity?: "LOW" | "MEDIUM" | "HIGH" | "CRITICAL";
  damageAmount?: number;
  aliases?: string[];
};

export const CATEGORIES: { slug: string; label: string }[] = [
  { slug: "theft", label: "Vehicle Theft / Attempted Theft" },
  { slug: "fraud", label: "Fraud / Fake ID / Identity Theft" },
  { slug: "damage", label: "Vehicle Damage / Crash" },
  { slug: "nonpayment", label: "Nonpayment / Chargeback" },
  { slug: "abandonment", label: "Abandonment / Nonresponsive" },
  { slug: "criminal", label: "Criminal Activity / Police Chase" },
  { slug: "unauthorized", label: "Unauthorized Driver / Sublease / Travel" },
  { slug: "hit-and-run", label: "Hit and Run" },
  { slug: "reckless", label: "Reckless Driving / Speeding" },
  { slug: "vandalism", label: "Vandalism / Property Damage" },
  { slug: "weapons", label: "Firearms / Shooting" },
];

export const SEED_ENTRIES: SeedEntry[] = [
  { fullName: "Aisha Mercedes Mccluster", primaryReason: "Crashed car and left it abandoned", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Akeil Byanille", primaryReason: "Caused $3,000 in damages; refused payment", categories: ["damage","nonpayment"], damageAmount: 3000, severity: "HIGH" },
  { fullName: "Akiem Rashid Williams", primaryReason: "Tried to steal vehicle; last seen at chop shop", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Aleysis Perez Xzavier", primaryReason: "Fraudulent payment and vehicle abandonment", categories: ["fraud","abandonment"], severity: "HIGH" },
  { fullName: "Alton Adolph III Burris Jr", primaryReason: "Nonpayment and property damage", categories: ["nonpayment","damage"], severity: "HIGH" },
  { fullName: "Amelia Williams", primaryReason: "Fraudulent identification", categories: ["fraud"], severity: "HIGH" },
  { fullName: "Amari Robert Bigger", primaryReason: "Reckless driving, hit-and-run, nonpayment", categories: ["reckless","hit-and-run","nonpayment"], severity: "CRITICAL" },
  { fullName: "Anastase Kabura", primaryReason: "Vehicle damage; nonresponsive", categories: ["damage","abandonment"], severity: "MEDIUM" },
  { fullName: "Anderson Jair Abreu", primaryReason: "Vehicle theft", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Andre Alexander Goldson", primaryReason: "Vehicle repossession; retained key", categories: ["theft","unauthorized"], severity: "HIGH" },
  { fullName: "Andy Stephano Delice", primaryReason: "Vehicle damage; abandonment", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Angelo Alante Pitt", primaryReason: "Curb-rash damage, smoking violation, hostile behavior", categories: ["damage"], severity: "MEDIUM" },
  { fullName: "Anthony Batson", primaryReason: "Fraudulent identification", categories: ["fraud"], severity: "HIGH" },
  { fullName: "Anthony Lashon Mclemore", primaryReason: "Attempted theft; vehicle trafficking", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Anthony Maya", primaryReason: "Multiple vehicle burglary charges", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Antwaney Jamilia Tinsely", primaryReason: "Identity fraud — fake license used by girlfriend", categories: ["fraud"], severity: "HIGH" },
  { fullName: "April Sharon Louise Robinson", primaryReason: "Multiple vehicle damage; hit-and-run; pursuit", categories: ["damage","hit-and-run","criminal"], severity: "CRITICAL" },
  { fullName: "Ariel Alonso Brown", primaryReason: "Grand theft auto; fleeing police", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Ariel Chanel Robertson", primaryReason: "Fraudulent payment attempt", categories: ["fraud","nonpayment"], severity: "HIGH" },
  { fullName: "Arties Tyriq", primaryReason: "Vehicle damage; theft of GPS equipment", categories: ["damage","theft"], severity: "HIGH" },
  { fullName: "Axcel Manuel Genao Carrasco", primaryReason: "Suspension damage; nonpayment ($861 owed)", categories: ["damage","nonpayment"], damageAmount: 861, severity: "MEDIUM" },
  { fullName: "Ayanna Leila Joseph", primaryReason: "Vehicle crash; nonpayment; fraudulent claim", categories: ["damage","nonpayment","fraud"], severity: "HIGH" },
  { fullName: "Aaron Jacob Frank", primaryReason: "Vehicle crash; nonresponsive", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Anyell Hernandez Valle", primaryReason: "Excessive mileage; attempted theft", categories: ["theft","unauthorized"], severity: "HIGH" },
  { fullName: "Adrian James Ellis", primaryReason: "Vehicle crash; nonresponsive", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Badin Junior Fundora", primaryReason: "Arrested in vehicle; evading police", categories: ["criminal"], severity: "CRITICAL" },
  { fullName: "Bennie III Jenkins", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Bijaun Wayne Edwards", primaryReason: "Unauthorized vehicle sublease; crash damage; nonpayment", categories: ["unauthorized","damage","nonpayment"], severity: "HIGH" },
  { fullName: "Brashard Javon Smith", primaryReason: "Vehicle crash; nonpayment; evasion", categories: ["damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Brandon Herbert Lee Walker", primaryReason: "Attempted theft; vehicle total loss", categories: ["theft","damage"], severity: "CRITICAL" },
  { fullName: "Brandon Japeth White", primaryReason: "Property damage ($1,200); abandonment; poor communication", categories: ["damage","abandonment"], damageAmount: 1200, severity: "MEDIUM" },
  { fullName: "Brandon Stevie Jr Washington", primaryReason: "Fraud; fake identification; insurance fraud", categories: ["fraud"], severity: "CRITICAL" },
  { fullName: "Britly Coraly Louis", primaryReason: "Payment default; vehicle damage; property theft", categories: ["nonpayment","damage","theft"], severity: "HIGH" },
  { fullName: "Broderick T JR Sandford", primaryReason: "Nonpayment ($1,500 owed)", categories: ["nonpayment"], damageAmount: 1500, severity: "MEDIUM" },
  { fullName: "Bryan Paul V Bernard", primaryReason: "Vehicle crash; abandonment; nonresponsive", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Bryan Zais Martinez", primaryReason: "Nonpayment; vehicle damage; vehicle disablement", categories: ["nonpayment","damage"], severity: "HIGH" },
  { fullName: "Calvin Bentley", primaryReason: "Criminal activity in vehicle; vehicle crash", categories: ["criminal","damage"], severity: "CRITICAL" },
  { fullName: "Candice Thomas", primaryReason: "Attempted theft scheme; coordinated fraud", categories: ["theft","fraud"], severity: "CRITICAL", aliases: ["Queen Mecca Arabia Thomas"] },
  { fullName: "Canion Demond Gerard", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Carl Anthony Jr Britton", primaryReason: "Attempted theft; GPS removal; police involvement", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Carlos Mondesir", primaryReason: "Attempted theft; vehicle total loss", categories: ["theft","damage"], severity: "CRITICAL" },
  { fullName: "Cassandra Sarah Jean", primaryReason: "Payment refusal despite agreed terms", categories: ["nonpayment"], severity: "MEDIUM" },
  { fullName: "Cedarian Carnell Camper", primaryReason: "Nonpayment; vehicle repossession; retained key", categories: ["nonpayment","theft"], severity: "HIGH" },
  { fullName: "Cedric Antonio Jr Paige", primaryReason: "Reckless driving; tires slashed; fuel contamination", categories: ["reckless","vandalism","damage"], severity: "CRITICAL" },
  { fullName: "Cedrick Junior Dorisca", primaryReason: "Armed robbery; criminal conspiracy", categories: ["criminal","weapons"], severity: "CRITICAL" },
  { fullName: "Chanita Rena Carter", primaryReason: "Facilitating criminal activity; vehicle abandonment", categories: ["criminal","abandonment"], severity: "HIGH" },
  { fullName: "Christopher James Jackson", primaryReason: "Broker theft from clients and owners", categories: ["fraud","theft"], severity: "CRITICAL" },
  { fullName: "Christopher Pietro Llera", primaryReason: "Property damage; lost key; nonpayment", categories: ["damage","nonpayment"], severity: "HIGH" },
  { fullName: "Christian Carter", primaryReason: "Vehicle theft", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Christian David Berrios", primaryReason: "Equipment damage; theft; abandonment", categories: ["damage","theft","abandonment"], severity: "HIGH" },
  { fullName: "Colby Jordan Hall", primaryReason: "Nonpayment ($1,520 owed); nonresponsive", categories: ["nonpayment","abandonment"], damageAmount: 1520, severity: "MEDIUM" },
  { fullName: "Collinwood Krisna Jr Darville", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Craig Aaron Vega", primaryReason: "Property damage; threatening behavior; deposit dispute", categories: ["damage","vandalism"], severity: "HIGH" },
  { fullName: "Dahl Janiel", primaryReason: "Nonpayment; unauthorized extension; vehicle retention", categories: ["nonpayment","unauthorized"], severity: "HIGH" },
  { fullName: "Dakodan Phenol El", primaryReason: "Vehicle crash; stolen credit card payment; nonresponsive", categories: ["damage","fraud","abandonment"], severity: "CRITICAL", aliases: ["Daolide El Mohyne"] },
  { fullName: "Dalian Trevon Smith", primaryReason: "Unauthorized vehicle sublease; crash; nonpayment", categories: ["unauthorized","damage","nonpayment"], severity: "HIGH" },
  { fullName: "Damian Calderon", primaryReason: "Speeding; crash; noncooperative with insurance", categories: ["reckless","damage"], severity: "HIGH" },
  { fullName: "Dandre Isaiah Campbell", primaryReason: "Attempted theft; fraudulent sale arrangement", categories: ["theft","fraud"], severity: "CRITICAL" },
  { fullName: "Daniel Jasse Leno", primaryReason: "Vehicle damage; nonpayment", categories: ["damage","nonpayment"], severity: "HIGH" },
  { fullName: "Darrold George Philias", primaryReason: "Refusal to return vehicle; chop shop delivery", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "D'Asia Amaiah Paul", primaryReason: "Unauthorized driver; crash; pursuit; nonresponsive", categories: ["unauthorized","damage","criminal","abandonment"], severity: "CRITICAL" },
  { fullName: "Daukaria Jaquoi Edwards", primaryReason: "Unauthorized sublease; crash; $7K damage; nonresponsive", categories: ["unauthorized","damage","abandonment"], damageAmount: 7000, severity: "CRITICAL" },
  { fullName: "David Jarrell Carpenter Jr", primaryReason: "Unauthorized travel; vehicle abandonment", categories: ["unauthorized","abandonment"], severity: "HIGH" },
  { fullName: "De'Michael Patrick Diah", primaryReason: "Property vandalism; hostile behavior", categories: ["vandalism","damage"], severity: "HIGH" },
  { fullName: "Deandry Jean", primaryReason: "Police chase; lost vehicle key; parking violations", categories: ["criminal","reckless"], severity: "HIGH" },
  { fullName: "Dejanzel Lewis", primaryReason: "Vehicle crash; abandonment; hostile response", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Dejonté Brendon Joseph", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Demar Khaliel Henry", primaryReason: "Vehicle nonreturn", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Demetrius Soffrant", primaryReason: "Vehicle crash; jurisdictional evasion", categories: ["damage","criminal"], severity: "HIGH" },
  { fullName: "Dennis Josue Castellanos", primaryReason: "Vehicle crash; abandonment; key theft", categories: ["damage","abandonment","theft"], severity: "HIGH" },
  { fullName: "Deonte Jamir Bradley", primaryReason: "Vehicle theft; nonresponsive", categories: ["theft","abandonment"], severity: "CRITICAL" },
  { fullName: "Deondre Ke'Yaun Joseph Robinson", primaryReason: "Vehicle abandonment; nonpayment; payment fraud", categories: ["abandonment","nonpayment","fraud"], severity: "HIGH" },
  { fullName: "Deshann Lewis Jr Roberson", primaryReason: "Vehicle damage; blocking contact", categories: ["damage","abandonment"], severity: "MEDIUM" },
  { fullName: "Deshon Kimani Collins", primaryReason: "Vehicle crash; jurisdictional evasion", categories: ["damage","criminal"], severity: "HIGH" },
  { fullName: "Deshannon Steven Michael Stubbs", primaryReason: "Unauthorized travel; nonpayment; attempted theft", categories: ["unauthorized","nonpayment","theft"], severity: "CRITICAL" },
  { fullName: "Devontae Nicholas Reid", primaryReason: "Abandonment; nonpayment; traffic violations; nonresponsive", categories: ["abandonment","nonpayment","reckless"], severity: "HIGH" },
  { fullName: "Dian Richards Khandai", primaryReason: "Property damage; lost key; nonpayment", categories: ["damage","nonpayment"], severity: "HIGH" },
  { fullName: "Dylan James Smith", primaryReason: "Arrest during rental; vehicle impound; damage; nonpayment", categories: ["criminal","damage","nonpayment"], severity: "CRITICAL" },
  { fullName: "Dylan Osvaldo Ryan Coe", primaryReason: "Nonpayment ($1,550 owed); abandonment", categories: ["nonpayment","abandonment"], damageAmount: 1550, severity: "MEDIUM" },
  { fullName: "Eduardo Jr Miranda", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Elaine De La Caridad Borrego Morejon", primaryReason: "Nonpayment for minor repairs", categories: ["nonpayment"], severity: "LOW" },
  { fullName: "Erika Monique Starkes", primaryReason: "Nonpayment ($600 owed); property infestation", categories: ["nonpayment","damage"], damageAmount: 600, severity: "MEDIUM" },
  { fullName: "Emmanuel Ernesto Fuentes", primaryReason: "Extensive vehicle damage; unresponsive to payment", categories: ["damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Emmanuel Levell Jr Lipscomb", primaryReason: "Vehicle damage; extended abandonment", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Felix Mejia Omar Jr", primaryReason: "Vehicle crash; nonresponsive; unauthorized brokers", categories: ["damage","abandonment","unauthorized"], severity: "HIGH" },
  { fullName: "Felix Mondy Vincent", primaryReason: "Renting to minor (age 16)", categories: ["unauthorized","fraud"], severity: "CRITICAL" },
  { fullName: "Fernando Jose Andrade", primaryReason: "Criminal activity in vehicle; crash; nonpayment", categories: ["criminal","damage","nonpayment"], severity: "CRITICAL" },
  { fullName: "Frank James Jr III", primaryReason: "Late payments; towing situation; key retention dispute", categories: ["nonpayment","unauthorized"], severity: "MEDIUM" },
  { fullName: "Gary Cameron Barriffe", primaryReason: "Vehicle total loss; nonresponsive", categories: ["damage","abandonment"], severity: "CRITICAL" },
  { fullName: "George Letrell III Rolle", primaryReason: "Police chase; vehicle abandonment", categories: ["criminal","abandonment"], severity: "CRITICAL" },
  { fullName: "Giancarlo Segura", primaryReason: "Hit-and-run; police chase; impound; nonpayment", categories: ["hit-and-run","criminal","nonpayment"], severity: "CRITICAL" },
  { fullName: "Giovanni Trostky Applyrs", primaryReason: "Vehicle theft (multiple attempts)", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Gladymir Steeve Altidor", primaryReason: "Vehicle shooting damage; nonpayment", categories: ["weapons","damage","nonpayment"], severity: "CRITICAL" },
  { fullName: "Hailey Lynn Carter", primaryReason: "Police chase during rental; nonpayment of deductible", categories: ["criminal","nonpayment"], severity: "HIGH" },
  { fullName: "Hans Verlin Dorvil", primaryReason: "Vehicle damage; abandonment", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Ismael Jeantinoble", primaryReason: "Excessive speeding; rule violations", categories: ["reckless"], severity: "HIGH" },
  { fullName: "Isaiah Luis Barsallo", primaryReason: "Police evasion; vehicle damage; arrest", categories: ["criminal","damage"], severity: "CRITICAL" },
  { fullName: "Isaiah Timothy Roche", primaryReason: "Hit-and-run; firearms abandoned in vehicle", categories: ["hit-and-run","weapons","criminal"], severity: "CRITICAL" },
  { fullName: "Ja'Corrian Maurice Farley", primaryReason: "Hit-and-run; vehicle abandonment", categories: ["hit-and-run","abandonment"], severity: "CRITICAL" },
  { fullName: "Jad Ali Zahr", primaryReason: "Vehicle theft", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Jaharty Lamar Walden", primaryReason: "Vehicle damage; chargeback fraud; account closure caused", categories: ["damage","fraud","nonpayment"], severity: "CRITICAL", aliases: ["Jahtary Lamar Walden"] },
  { fullName: "Jahmal Blake Michel", primaryReason: "Armed robbery; extortion during rental", categories: ["criminal","weapons"], severity: "CRITICAL" },
  { fullName: "Jahvon Alphonso Smith", primaryReason: "Fraudulent payment attempt", categories: ["fraud","nonpayment"], severity: "HIGH" },
  { fullName: "Jamie Valencia Taylor", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Jamall Guy Compere", primaryReason: "Property vandalism; nonpayment", categories: ["vandalism","nonpayment"], severity: "HIGH" },
  { fullName: "Jameson Juste", primaryReason: "Vehicle crash; nonpayment outstanding since May", categories: ["damage","nonpayment"], severity: "HIGH" },
  { fullName: "Jamira Marie Gibbons", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Janarry Renard Berry", primaryReason: "Unauthorized driver; vehicle crash; nonpayment", categories: ["unauthorized","damage","nonpayment"], severity: "HIGH" },
  { fullName: "Jaquan Brown", primaryReason: "Fraudulent identification", categories: ["fraud"], severity: "HIGH" },
  { fullName: "Jarrett Dajuan Beal", primaryReason: "Cash theft (DFW, TX location)", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Jarvis Brandon Lewis", primaryReason: "Attempted vehicle robbery; transport scheme", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Jasmien Marie Pryor", primaryReason: "Unauthorized travel; vehicle total loss; evasion", categories: ["unauthorized","damage","abandonment"], severity: "CRITICAL" },
  { fullName: "Jatavius Jabare Austin", primaryReason: "Attempted vehicle theft; key retention", categories: ["theft"], severity: "HIGH" },
  { fullName: "Jayden Alex Lawson", primaryReason: "Vehicle damage; nonpayment; excuse patterns", categories: ["damage","nonpayment"], severity: "MEDIUM" },
  { fullName: "Jayden Octavious Pendergrass", primaryReason: "Multiple grand theft auto charges", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Jaylen Marie Belis", primaryReason: "Vehicle crash; payment default; nonresponsive", categories: ["damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Jaylen Nathan Stokes", primaryReason: "Vehicle nonreturn", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Jaylen Paul Chambers", primaryReason: "Vehicle abandonment; nonresponsive", categories: ["abandonment"], severity: "HIGH" },
  { fullName: "Jazniel Marie Pryor", primaryReason: "Unauthorized travel; vehicle total loss", categories: ["unauthorized","damage"], severity: "CRITICAL" },
  { fullName: "Jerriesha Chantel Brown", primaryReason: "Facilitating criminal activity by juveniles", categories: ["criminal"], severity: "CRITICAL" },
  { fullName: "Jeremiah Isaiah Stewart", primaryReason: "Vehicle crash; abandonment; nonpayment", categories: ["damage","abandonment","nonpayment"], severity: "HIGH" },
  { fullName: "Jeremiah Pierre Tassy", primaryReason: "Vehicle crash; highway abandonment", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Jeremy Kevan Carr", primaryReason: "Theft history; deceptive rental application", categories: ["theft","fraud"], severity: "HIGH" },
  { fullName: "Jermaine Jarvis Jr Hall", primaryReason: "Nonpayment; property damage; incarceration during rental", categories: ["nonpayment","damage","criminal"], severity: "CRITICAL" },
  { fullName: "Jeffrey Mertilus", primaryReason: "Vehicle crash; nonpayment; nonresponsive", categories: ["damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Jevon Bernard", primaryReason: "Vehicle crash; abandonment; blame shifting", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Johanna Lopez", primaryReason: "Unauthorized driver; vehicle total loss (fraudulent claim)", categories: ["unauthorized","damage","fraud"], severity: "CRITICAL" },
  { fullName: "John Howard Wiegand", primaryReason: "Time-wasting rental request; no-show", categories: ["fraud"], severity: "LOW" },
  { fullName: "John Michael Marshall", primaryReason: "Late payments; vehicle abandonment; evasion", categories: ["nonpayment","abandonment"], severity: "MEDIUM" },
  { fullName: "Jonathan Louis Fernandez", primaryReason: "Vehicle theft", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Jordan Alexander Ewing", primaryReason: "Invoice fraud scheme", categories: ["fraud"], severity: "HIGH" },
  { fullName: "Jordan Amias Hazarian", primaryReason: "Unauthorized sublease; insurance fraud; lying", categories: ["unauthorized","fraud"], severity: "CRITICAL" },
  { fullName: "Jordan Ivan Pierre", primaryReason: "Vehicle accident; nonresponsive; insurance evasion", categories: ["damage","abandonment","fraud"], severity: "HIGH" },
  { fullName: "Jordan Mario Felix", primaryReason: "Police chase; crash; nonpayment", categories: ["criminal","damage","nonpayment"], severity: "CRITICAL" },
  { fullName: "Joseph Patrick McDonald Jr", primaryReason: "Identity fraud; fake license", categories: ["fraud"], severity: "CRITICAL" },
  { fullName: "Joshua Frank Botella", primaryReason: "Broker fraud; fake insurance; vehicle tracking removal", categories: ["fraud","theft"], severity: "CRITICAL" },
  { fullName: "Joshua Schneider Oerelus", primaryReason: "Vehicle crash; nonpayment; nonresponsive", categories: ["damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Julian JNBaptiste", primaryReason: "Fraudulent identification", categories: ["fraud"], severity: "HIGH" },
  { fullName: "Juwensky Shello Niclasse", primaryReason: "Vehicle crash; abandonment; threatening behavior", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Kadyn Mathew La'Shaun Cureton", primaryReason: "Excessive speeding (130+ mph); smoking; nonpayment; abandonment", categories: ["reckless","nonpayment","abandonment"], severity: "CRITICAL" },
  { fullName: "Kaleb Akim Campbell", primaryReason: "Unauthorized driver; vehicle total loss", categories: ["unauthorized","damage"], severity: "CRITICAL" },
  { fullName: "Karlensky Leger", primaryReason: "Vehicle crash; abandonment; threatening behavior", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Karmel Kushawn Green", primaryReason: "Unauthorized driver; vehicle crash; nonpayment", categories: ["unauthorized","damage","nonpayment"], severity: "HIGH" },
  { fullName: "Kellan Emmanuel Silver", primaryReason: "Police chase during rental; nonpayment of deductible", categories: ["criminal","nonpayment"], severity: "HIGH" },
  { fullName: "Keyshawn Jean Louis", primaryReason: "Vehicle crash; abandonment", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Kidron Anthony Mayes", primaryReason: "Reckless driving; vehicle abandonment; key retention", categories: ["reckless","abandonment"], severity: "HIGH" },
  { fullName: "Kurtis Peterson", primaryReason: "Payment evasion; fraudulent identification", categories: ["nonpayment","fraud"], severity: "HIGH" },
  { fullName: "Kylen Xavery Vonnae Penson", primaryReason: "Vehicle crash; nonpayment", categories: ["damage","nonpayment"], severity: "HIGH" },
  { fullName: "Lanard Dontae Jr Mc Cray", primaryReason: "Vehicle crash; nonresponsive", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Leodan Carbonell Vargas", primaryReason: "Vehicle theft", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Leonel Jorellus Jr", primaryReason: "Fraudulent payment confirmation", categories: ["fraud","nonpayment"], severity: "HIGH" },
  { fullName: "Levasiyea Laroi Jr Freeman", primaryReason: "Nonpayment; property damage", categories: ["nonpayment","damage"], severity: "MEDIUM" },
  { fullName: "Leythan Manotos", primaryReason: "Vehicle damage; shooting incident; nonresponsive", categories: ["damage","weapons","abandonment"], severity: "CRITICAL" },
  { fullName: "Lewis Twistan Larose", primaryReason: "T-bone crash; nonpayment; nonresponsive", categories: ["damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Liam Harnold", primaryReason: "Listed on do-not-rent registry", categories: ["fraud"], severity: "MEDIUM" },
  { fullName: "Louis Archange Joseph", primaryReason: "Nonpayment; vehicle disablement", categories: ["nonpayment"], severity: "MEDIUM" },
  { fullName: "Louis Geogre", primaryReason: "Vehicle crash; abandonment; fraudulent repair claim", categories: ["damage","abandonment","fraud"], severity: "HIGH" },
  { fullName: "Malik Khalil Early", primaryReason: "Vehicle theft; tracker removal; Instagram resale attempt", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Malik Yeman Warren", primaryReason: "Late payments; blocking contact; vehicle abuse", categories: ["nonpayment","damage"], severity: "HIGH" },
  { fullName: "Malachi Akio Justin", primaryReason: "Vehicle nonreturn; unauthorized transport; property damage", categories: ["theft","unauthorized","damage"], severity: "CRITICAL" },
  { fullName: "Manso Emanuel Athitakis", primaryReason: "Vehicle destruction; theft", categories: ["theft","damage"], severity: "CRITICAL" },
  { fullName: "Marquez Deandre Handspike", primaryReason: "Nonpayment; false damage claim; abandonment", categories: ["nonpayment","fraud","abandonment"], severity: "HIGH" },
  { fullName: "Marcus Justin White", primaryReason: "Multiple vehicle theft attempts", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Marvin Ricky Obsaint", primaryReason: "Property vandalism; nonpayment", categories: ["vandalism","nonpayment"], severity: "HIGH" },
  { fullName: "Matthew Brown", primaryReason: "Vehicle crash; nonresponsive", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Mccoy Dejuane ZO", primaryReason: "Fraudulent ID; shooting incident; insufficient funds", categories: ["fraud","weapons","nonpayment"], severity: "CRITICAL" },
  { fullName: "Mckenzie Leigh Carney", primaryReason: "Unauthorized driver; DUI; hit-and-run", categories: ["unauthorized","reckless","hit-and-run"], severity: "CRITICAL" },
  { fullName: "Michael Adolfo Diaz", primaryReason: "Broker theft of rental profits", categories: ["fraud","theft"], severity: "CRITICAL", aliases: ["Flakko"] },
  { fullName: "Michael Anthony Jr Thomas", primaryReason: "Crash; DUI; nonpayment ($15K damage)", categories: ["damage","reckless","nonpayment"], damageAmount: 15000, severity: "CRITICAL" },
  { fullName: "Michael Donald 3RD Holman", primaryReason: "Vehicle damage; nonpayment; abandonment", categories: ["damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Michelle Casey Allan", primaryReason: "Nonpayment; vehicle abandonment; nonresponsive", categories: ["nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Mi'kayla Ayani Rivers", primaryReason: "Vehicle damage; unauthorized driver; nonpayment", categories: ["damage","unauthorized","nonpayment"], severity: "HIGH" },
  { fullName: "Mitchell Don Eadens", primaryReason: "Fraudulent identification", categories: ["fraud"], severity: "HIGH" },
  { fullName: "Mithal Eddine Soudani", primaryReason: "Complaint patterns; vehicle damage; threatening behavior", categories: ["damage"], severity: "MEDIUM" },
  { fullName: "Mitch Norrell Kent", primaryReason: "Unauthorized driver; vehicle damage; nonpayment; nonresponsive", categories: ["unauthorized","damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Myron Alphonso Levy", primaryReason: "Attempted vehicle theft (warehouse hiding)", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Nelson Na'Twan Jr Cross", primaryReason: "Fraudulent identification; attempted theft", categories: ["fraud","theft"], severity: "CRITICAL" },
  { fullName: "Nicholas Alexander Martinez", primaryReason: "Unauthorized travel; vehicle abuse; multiple violations; dishonesty", categories: ["unauthorized","damage","fraud"], severity: "HIGH" },
  { fullName: "Nickalus Jamicheal Walters", primaryReason: "Unauthorized driver; vehicle crash; nonresponsive", categories: ["unauthorized","damage","abandonment"], severity: "HIGH" },
  { fullName: "Oliver Civil Newcome", primaryReason: "Scammer status; warrants in multiple states; theft history", categories: ["fraud","theft","criminal"], severity: "CRITICAL" },
  { fullName: "Omarion Ishmael Brookins", primaryReason: "Vehicle theft", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Oscar Martinez", primaryReason: "Multiple damage; unauthorized sublease; $5K+ damage; nonpayment", categories: ["damage","unauthorized","nonpayment"], damageAmount: 5000, severity: "CRITICAL" },
  { fullName: "Odrin Je'Paul Francois", primaryReason: "Vehicle crash; abandonment; nonpayment", categories: ["damage","abandonment","nonpayment"], severity: "HIGH" },
  { fullName: "Paul Michael Evans", primaryReason: "Attempted vehicle theft; license plate changing", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Philip Robert Gallina", primaryReason: "Nonpayment; vehicle abandonment; nonresponsive", categories: ["nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Pierre Dely Neptune", primaryReason: "Reckless driving; property vandalism", categories: ["reckless","vandalism"], severity: "HIGH" },
  { fullName: "Pollard Seth Lechard", primaryReason: "Vehicle theft", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Quincy Marshawn Milhomme", primaryReason: "Armed robbery; extortion during rental", categories: ["criminal","weapons"], severity: "CRITICAL" },
  { fullName: "Raheem Deshay Gaines", primaryReason: "Fraudulent payment; attempted vehicle theft", categories: ["fraud","theft"], severity: "CRITICAL" },
  { fullName: "Rahen Redji Bienne", primaryReason: "Nonpayment ($600 owed); nonresponsive", categories: ["nonpayment","abandonment"], damageAmount: 600, severity: "MEDIUM" },
  { fullName: "Raul Davian Bultron Rodriguez", primaryReason: "Nonpayment; property theft (vehicle mats)", categories: ["nonpayment","theft"], severity: "MEDIUM" },
  { fullName: "Readon Eric Dion", primaryReason: "Unauthorized sublease; nonpayment; customer deposit theft", categories: ["unauthorized","nonpayment","theft"], severity: "CRITICAL" },
  { fullName: "Renaldo Jr Cockrum", primaryReason: "Unauthorized travel; vehicle abandonment", categories: ["unauthorized","abandonment"], severity: "HIGH" },
  { fullName: "Robert J Istwan", primaryReason: "Fraudulent identification/information", categories: ["fraud"], severity: "HIGH" },
  { fullName: "Rodrigo Pinilla", primaryReason: "Police chase; vehicle crash; nonresponsive", categories: ["criminal","damage","abandonment"], severity: "CRITICAL" },
  { fullName: "Roland Guillaume", primaryReason: "Vehicle crash; nonpayment", categories: ["damage","nonpayment"], severity: "HIGH" },
  { fullName: "Ronald Alexander III Moss", primaryReason: "Unauthorized sublease; nonpayment; damage; criminal activity", categories: ["unauthorized","nonpayment","damage","criminal"], severity: "CRITICAL" },
  { fullName: "Roy Martinez", primaryReason: "Nonreturn; evasion with false arrest claim", categories: ["theft","fraud"], severity: "CRITICAL" },
  { fullName: "Samuel John Vincent Mccauley", primaryReason: "Vehicle damage; nonpayment; nonresponsive", categories: ["damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Santana De Jesus", primaryReason: "Payment chargeback fraud", categories: ["fraud","nonpayment"], severity: "HIGH" },
  { fullName: "Scott Ta'shi Nasharrie", primaryReason: "Attempted vehicle theft during transport", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Shaddai Daplinu Dunbar", primaryReason: "Reformed - removed from active warnings", categories: [], severity: "LOW" },
  { fullName: "Shameka Shuntay Bodie", primaryReason: "Vehicle sublease to son; $7,515 damage; nonresponsive", categories: ["unauthorized","damage","abandonment"], damageAmount: 7515, severity: "CRITICAL" },
  { fullName: "Shawn Marshall Mbugu Matambo", primaryReason: "Unauthorized driver; property damage; nonpayment", categories: ["unauthorized","damage","nonpayment"], severity: "HIGH" },
  { fullName: "Sheniece Chelsey Phillips", primaryReason: "Property infestation; payment fraud; sob stories", categories: ["damage","fraud","nonpayment"], severity: "HIGH" },
  { fullName: "Shianne Kiarrah Floyd", primaryReason: "Vehicle damage; abandonment (24+ hours)", categories: ["damage","abandonment"], severity: "MEDIUM" },
  { fullName: "Sonita Patrice Adolphe", primaryReason: "Vehicle shooting damage; nonpayment", categories: ["weapons","damage","nonpayment"], severity: "CRITICAL" },
  { fullName: "Souli Roldson Louis", primaryReason: "Criminal activity; police chase; damage; nonresponsive", categories: ["criminal","damage","abandonment"], severity: "CRITICAL" },
  { fullName: "Spinsir Easley", primaryReason: "Vehicle theft; transport to another state", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Stefany Hernandez Alvarez", primaryReason: "Vehicle theft claim; vehicle nonrecovery", categories: ["theft","fraud"], severity: "CRITICAL" },
  { fullName: "Stephane Joseph", primaryReason: "Vehicle crash; nonpayment", categories: ["damage","nonpayment"], severity: "HIGH" },
  { fullName: "Steven Ray Michael Townes", primaryReason: "Vehicle theft", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Steve Durand", primaryReason: "Vehicle total loss; flight from scene", categories: ["damage","hit-and-run"], severity: "CRITICAL" },
  { fullName: "Tavares Lamar Jr Rickerson", primaryReason: "False damage report; vehicle total loss", categories: ["fraud","damage"], severity: "CRITICAL" },
  { fullName: "Taylor Cameron Jharrod", primaryReason: "Vehicle total loss; nonpayment", categories: ["damage","nonpayment"], severity: "CRITICAL" },
  { fullName: "Tejan Jahki Smith", primaryReason: "Unauthorized driver; vehicle damage; nonpayment; nonresponsive", categories: ["unauthorized","damage","nonpayment","abandonment"], severity: "HIGH" },
  { fullName: "Tevin Joseph Reed", primaryReason: "Property damage due to complaint; blocking contact", categories: ["damage","abandonment"], severity: "MEDIUM" },
  { fullName: "Teya Jenilee Perkins", primaryReason: "Attempted vehicle theft; border evasion attempt", categories: ["theft","criminal"], severity: "CRITICAL" },
  { fullName: "Thadoeus Squire III", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Traivon Ramone Greene Trice", primaryReason: "Vehicle total loss; abandonment", categories: ["damage","abandonment"], severity: "CRITICAL" },
  { fullName: "Trakia D'ahjanae Mccoy", primaryReason: "Vehicle crash; haphazard abandonment", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Treyshawn Dionte Wright", primaryReason: "Late payment; vehicle disablement; blocking contact", categories: ["nonpayment"], severity: "MEDIUM" },
  { fullName: "Tremanye Leon Jr Nottage", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Travia Lakiyra Williams", primaryReason: "Unauthorized driver; attempted theft; required steering lock", categories: ["unauthorized","theft"], severity: "CRITICAL" },
  { fullName: "Tylen Keyshawn Bush", primaryReason: "Vehicle damage; nonpayment", categories: ["damage","nonpayment"], severity: "HIGH" },
  { fullName: "Tyler Darrell Treasure", primaryReason: "Reckless; multiple hit-and-runs; abandonment; $8K+ damage", categories: ["reckless","hit-and-run","abandonment","damage"], damageAmount: 8000, severity: "CRITICAL" },
  { fullName: "Tyler Vernel Rattray", primaryReason: "Vehicle crash; abandonment; nonresponsive", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Tyrone Antonio Jr Walker", primaryReason: "Vehicle damage; nonpayment", categories: ["damage","nonpayment"], severity: "HIGH" },
  { fullName: "Tykwon Deandre Anderson", primaryReason: "Vehicle crash; nonresponsive", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Victor Muriuki", primaryReason: "Unauthorized driver; property damage; nonpayment", categories: ["unauthorized","damage","nonpayment"], severity: "HIGH" },
  { fullName: "Victor Tobenna Ilomuanya", primaryReason: "Unauthorized vehicle sale arrangement", categories: ["unauthorized","theft"], severity: "CRITICAL" },
  { fullName: "Vivian Anthony Franklyn Bedward", primaryReason: "Fraudulent payment; vehicle abandonment", categories: ["fraud","abandonment"], severity: "HIGH" },
  { fullName: "Vontahj Eugene Montesse Mcguire", primaryReason: "Unauthorized travel (Vegas to Michigan); recovery incident", categories: ["unauthorized"], severity: "HIGH" },
  { fullName: "William Robert James Jr", primaryReason: "Nonpayment of parking tickets ($800+)", categories: ["nonpayment"], damageAmount: 800, severity: "MEDIUM" },
  { fullName: "Williams Zamari Shalique", primaryReason: "Vehicle damage; nonresponsive", categories: ["damage","abandonment"], severity: "HIGH" },
  { fullName: "Wilkinson Pierrelouis", primaryReason: "Vehicle theft", categories: ["theft"], severity: "CRITICAL" },
  { fullName: "Xzavier Aleysis Perez", primaryReason: "Fraudulent payment; abandoned vehicle", categories: ["fraud","abandonment"], severity: "HIGH" },
  { fullName: "Yesenia Torres Sanchez", primaryReason: "Attempted vehicle theft", categories: ["theft"], severity: "HIGH" },
  { fullName: "Yesika Garcia", primaryReason: "Vehicle shooting damage; abandonment", categories: ["weapons","damage","abandonment"], severity: "CRITICAL" },
  { fullName: "Zachary Adonis Philippe", primaryReason: "Unauthorized sublease; nonpayment; multiple crashes", categories: ["unauthorized","nonpayment","damage"], severity: "CRITICAL" },
];
